#!/usr/bin/python

import sys

width = int(sys.argv[1])
rate = float(sys.argv[2])
height = int(width * 9.0/16.0)
seconds = int(width * height / rate)
h = seconds/3600
m = (seconds - h * 3600)/60
s = seconds % 60
print "Projected time for {}x{}: {}:{}:{} | {}".format(width, height, h, m, s, seconds)

